### ISSUE TITLE
@capacitor-community/stripe crashes the app on android 14 

### ISSUE THREAD

**Issue by teebaeze** [capacitor-community/stripe#336]
Platform: Android ionic 6 capacitor

I discovered that on Android 14 devices after it is being built with @capacitor-community  it crashes the app on launch and immediately the package is being removed the app works normal
Log of the crash below

--------- beginning of crash
02-07 23:13:32.958 3557 3557 E AndroidRuntime: FATAL EXCEPTION: main
02-07 23:13:32.958 3557 3557 E AndroidRuntime: Process: com.salon.home, PID: 3557
02-07 23:13:32.958 3557 3557 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver de.appplant.cordova.plugin.localnotification.RestoreReceiver: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:4499)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:205)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.os.Looper.loop(Looper.java:294)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8248)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:604)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:587)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:221)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:221)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at de.appplant.cordova.plugin.notification.Manager.getPrefs(Manager.java:399)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at de.appplant.cordova.plugin.notification.Manager.getIds(Manager.java:206)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at de.appplant.cordova.plugin.notification.Manager.getOptions(Manager.java:291)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at de.appplant.cordova.plugin.notification.receiver.AbstractRestoreReceiver.onReceive(AbstractRestoreReceiver.java:64)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:4490)
02-07 23:13:32.958 3557 3557 E AndroidRuntime: ... 9 more
02-07 23:13:33.015 3574 3574 E AndroidRuntime: FATAL EXCEPTION: main
02-07 23:13:33.015 3574 3574 E AndroidRuntime: Process: com.salon.home.qa, PID: 3574
02-07 23:13:33.015 3574 3574 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver de.appplant.cordova.plugin.localnotification.RestoreReceiver: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked

**Expected behavior**
The app is supposed to run smoothly and not crash

**Usage Product**
@capacitor-community/stripe

**Comment by rdlabo** [comment]
Close this log as there is nothing from Stripe in this log.
